### ISSUE TITLE
Setting page design 

### ISSUE THREAD

**Issue by itschetu** [premAI-io/prem-app#121]
setting page design should be same as figma 
--------------------------------

![image](https://github.com/premAI-io/prem-app/assets/136341886/507a7783-4cc7-4dbf-817c-242d22c1b206)
 
 Figma Design ::
 ----------------------
 
![image](https://github.com/premAI-io/prem-app/assets/136341886/6f6b6817-5b60-4685-b102-5c32cfb72d25)

**Comment by hardik-rl** [comment]
hamburger menu already fixed in Mr #119
