### ISSUE TITLE
Card Image radius

### ISSUE THREAD

**Issue by itschetu** [premAI-io/prem-app#124]
In card image radius looks good from right/left but from top and bottom it's bit out 
![image](https://github.com/premAI-io/prem-app/assets/136341886/aaac5fd3-e6fa-4ddf-bc7c-c9b67887b115)

**Comment by hardik-rl** [comment]
it's Icon issue,
just replace Icon in backend,
filippopedrazzinifp can you replace Icon,
as per our slack discussion, link below here, 
https://prem-qzb5529.slack.com/archives/C05BNHG4NLV/p1686734382281449
