### ISSUE TITLE
Text: Update button in navbar

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#148]
![image](https://github.com/premAI-io/prem-app/assets/3596602/6040dcd7-2c51-4d37-8239-273076f8213c)

The update button 

- ONLY appear if there is a greater version available. 
- The tooltip should say `There is a new version available for this service. Updating will dowload the new version and restart your service, causing a brief downtime`

**Comment by jigneshsolanki** [comment]
@tiero Update button will only display if `needsUpdate` is true from backend
