### ISSUE TITLE
Search filter in mobile

### ISSUE THREAD

**Issue by itschetu** [premAI-io/prem-app#158]
In responsive the the search filter bar showing with while border line 
![image](https://github.com/premAI-io/prem-app/assets/136341886/c44b8168-a155-4051-9747-14854eae1f0d)

**Comment by hardik-rl** [comment]
currently not coming issue, 
please close this tickets, 
@filippopedrazzinifp

**Comment by itschetu** [comment]
please check in main 
![image](https://github.com/premAI-io/prem-app/assets/136341886/5db8b325-0793-4cac-bbef-2f016874f28e)

**Comment by itschetu** [comment]
moving this issue to another ticket
