### ISSUE TITLE
Running `npm run tauri dev` throws an error message: "No such file or directory" }', src/interface/rust.rs:762:69"

### ISSUE THREAD

**Issue by NonMundaneDev** [premAI-io/prem-app#161]
Hi,

When I clone prem-app and attempt to un:

`npm i` (works)

and then:

`npm run tauri dev`

> Reference: https://github.com/premAI-io/prem-app/blob/c518fa3c41c4bb58334c3ca7fc719d7d16c362e1/README.md?plain=1#L75-L77

It throws the following error on a MacBook M1 Pro device (terminal):

```
> prem-app@0.0.15 tauri
> tauri dev

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I made sure to run `docker-compose down` to stop and remove all prior prem containers. I also pulled the latest release `v0.0.12`.

**Comment by jigneshsolanki** [comment]
Hi @NonMundaneDev,

For tauri, You need to install Rust.

Please check Prerequisites here: https://tauri.app/v1/guides/getting-started/prerequisites
