### ISSUE TITLE
Chat: scrolling bugs

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#170]
[Screencast_from_21.06.2023_122508(1).webm](https://github.com/premAI-io/prem-app/assets/3596602/fc4d4523-9718-4060-804a-a87de58ce674)
[Screencast_from_21.06.2023_122508.webm](https://github.com/premAI-io/prem-app/assets/3596602/1c902356-78ae-4a2f-9d48-e7454b30b7ff)

**Comment by tiero** [comment]
ping @hardik-rl @jigneshsolanki 
![image](https://github.com/premAI-io/prem-app/assets/3596602/16ee60b2-d6e5-4fe9-ba40-bf096a0990dd)

**Comment by tiero** [comment]
Whats the status of this?

**Comment by itschetu** [comment]
the scroll issue is fixed in this PR and for other issue i have created ticket before so closing this 

Ticket : [(https://github.com/premAI-io/prem-app/issues/169)]
