### ISSUE TITLE
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by zugaldia** [premAI-io/prem-app#202]
I just tried the install instructions (`wget -q https://get.prem.ninja/install.sh -O install.sh; sudo bash ./install.sh`) on a Linux Ubuntu 22.04 LTS machine with CUDA installed and I got the error in the title:

```
👷‍♂️ Installing Prem
⬇️ Pulling latest version...
App Version: v0.0.17
App Image: ghcr.io/premai-io/prem-app
App Digest: sha256:c1522bb0ebd5be02346127855e2d943ec022c59c9268a02ee1ef672a61904ea9
Daemon Version: v0.0.15
Daemon Image: ghcr.io/premai-io/premd
Daemon Digest: sha256:abcd6994db1dfad1df8210ae3d2a5863d2b68045f82d00c1c0c9d7a1add2865b
🏁 Starting Prem...
nvidia-smi is available. Running docker-compose.gpu.yml
[+] Running 2/3
 ✔ Container caddy     Running                                                                                 0.0s 
 ✔ Container prem_app  Running                                                                                 0.0s 
 ⠹ Container premd     Starting                                                                                0.3s 
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
```

Anything I could to help troubleshoot?

**Comment by ImayaBharathi** [comment]
We need NVIDIA Container Toolkit for container to access GPU. These are the steps that i followed for sucessfull prem-app setup.

- `. /etc/os-release;echo $ID$VERSION_ID`  => to get your system distribution.
- `export distribution=ubuntu20.04`
- `curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -`
- `curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list`
- `sudo apt-get update`
- `sudo apt-get install -y nvidia-docker2`
- `sudo systemctl restart docker`
After this you can run `sudo bash install.sh` to get the prem app running on GPU.
Hope this helps.

i would be happy to take this issue, if no one is working on it. @team let me know.

**Comment by filippopedrazzinifp** [comment]
Yes @ImayaBharathi, it would be awesome. Can you create a PR in prem-box https://github.com/premAI-io/prem-box

**Comment by ImayaBharathi** [comment]
Sure, will do. thanks

**Comment by filopedraz** [comment]
Closing this. It has been fixed in prem-box.
