### ISSUE TITLE
No Getting started code for Vicuna 7B Q4 using embedding

### ISSUE THREAD

**Issue by billmetangmo** [premAI-io/prem-app#221]
Hello,

I installed premAI on a server then Vicuna 7B Q4.
However, I don't see an example of Getting started when i clicked on to vicuna embeddings
It's the same than vicuna chat.

I expected to have a getthin g started code like the ones from All MiniLM L6 v2

**Comment by filippopedrazzinifp** [comment]
Hello @billmetangmo, the logic is the following:

If a service has multiple interfaces (Chat, Embeddings) and one of the interfaces has a playground, then it will open the playground. On the other hand, you can check the swagger of the service at the link provided in the service detail view.

<img width="741" alt="image" src="https://github.com/premAI-io/prem-app/assets/29598954/3bd64c90-f684-48c5-b42a-e835c25365a6">

Let me know it it helps. If you are looking for a more direct support you can join our discord: https://discord.com/invite/kpKk6vYVAn

**Comment by billmetangmo** [comment]
Thanks for answer @filippopedrazzinifp 
This issue was part of my question on Discord #support .

I succeeded to create embeddings using API request i got from swagger.
However it don't work when i try:

```python
import os

from langchain.embeddings import OpenAIEmbeddings

os.environ["OPENAI_API_KEY"] = "random-string"

embeddings = OpenAIEmbeddings(openai_api_base="http://localhost:8111/v1")
text = "Prem is an easy to use open source AI platform."
query_result = embeddings.embed_query(text)
doc_result = embeddings.embed_documents([text])
```

taking inspiration from playground of All MiniLM L6 v2

**Comment by billmetangmo** [comment]
Your answer on Discord closes this issue.
I create a new one: for https://github.com/premAI-io/prem-app/issues/225
