### ISSUE TITLE
PREM audio to text 

### ISSUE THREAD

**Issue by itschetu** [premAI-io/prem-app#233]
1. remove scroll from header keep the scroll in middle body 
![image](https://github.com/premAI-io/prem-app/assets/136341886/682fe669-1b13-4f65-9e2a-a4c77f037f4c)

2. icon missing in sidebar 
![image](https://github.com/premAI-io/prem-app/assets/136341886/fd226903-a489-4243-8e65-1578e819c453)

3.if audio file name is long then design break
![image](https://github.com/premAI-io/prem-app/assets/136341886/ae528e91-6fce-4acb-9ffa-a09a4fd53976)
![image](https://github.com/premAI-io/prem-app/assets/136341886/10805107-2e9a-4824-bbb7-a646e5963638)

4. show validation message for invalid file 

5. remove hover effect on submit button if button is disable 
 
6.  can we show uploaded file with diff text or style it is looks as normal text 
![image](https://github.com/premAI-io/prem-app/assets/136341886/952e4a36-3ecd-4eed-ae8e-07dac50a6fa3)

7. remove uploaded file if user click on previous result
[Prem---Self-Sovereign-AI-Infrastructure (5).webm](https://github.com/premAI-io/prem-app/assets/136341886/20b38d0e-cb5c-4a24-8d34-1aa491e35a1c)

 8. mobile > close sidebar after click on prev search 
 
 9. make submit and cancel button align with upper box 
![image](https://github.com/premAI-io/prem-app/assets/136341886/928497e8-9bd0-474a-aeb1-ec9765de7435)
 
10. icon not looking as in centre
![image](https://github.com/premAI-io/prem-app/assets/136341886/88c72c6f-b7e7-4553-9f6e-ef027bac8862)

11. there is one line at bottom text remove it 
![image](https://github.com/premAI-io/prem-app/assets/136341886/4654b403-bf3e-488b-970d-50be14aac310)

12. add scroll to output result instead of increasing model size
![image](https://github.com/premAI-io/prem-app/assets/136341886/112b555e-45be-4ea4-8353-415c0972ce4f)

13. remove background image for mobile
![image](https://github.com/premAI-io/prem-app/assets/136341886/51de9b9f-0082-4419-8c4f-a300a9aa4b02)

14. change design for result image in mobile 
![image](https://github.com/premAI-io/prem-app/assets/136341886/015e308e-f598-42b2-b338-2be478a9db47)

**Comment by filopedraz** [comment]
@hardik-rl no need for (2)

**Comment by itschetu** [comment]
@hardik-rl please check updated list
