### ISSUE TITLE
Possibility to append a new registry url

### ISSUE THREAD

**Issue by filopedraz** [premAI-io/prem-app#242]
### Description 

User can attach another registry from the settings page

<img width="793" alt="image" src="https://github.com/premAI-io/prem-app/assets/29598954/a859fd87-6527-49e9-85c5-f7e45f1bee66">

New Endpoints available to GET and POST

<img width="1547" alt="image" src="https://github.com/premAI-io/prem-app/assets/29598954/b8bb3323-b31c-4ec2-825f-ed635d50833a">

**Comment by itschetu** [comment]
@hardik-rl 
please check design for mobile and desktop both 
Ref. -->  Figma
![image](https://github.com/premAI-io/prem-app/assets/136341886/77ac1653-0d7e-4bca-acab-40fa90318b26)

![image](https://github.com/premAI-io/prem-app/assets/136341886/f70b709f-7965-4b84-949d-de32ff932706)

**Comment by Janaka-Steph** [comment]
> ![image](https://user-images.githubusercontent.com/136341886/252880358-f70b709f-7965-4b84-949d-de32ff932706.png)

This mobile screen has been updated on Figma right?
