### ISSUE TITLE
keep continue service download if user change/ go to any details page

### ISSUE THREAD

**Issue by itschetu** [premAI-io/prem-app#255]
[Prem---Self-Sovereign-AI-Infrastructure (2).webm](https://github.com/premAI-io/prem-app/assets/136341886/c53dd74e-ed71-43a1-bf28-92b4d8ec6b71)

**Comment by Janaka-Steph** [comment]
I noticed that also. It does continue downloading even if we go to an other page, we can see `Downloading` log messages. But the React state seems lost.

**Comment by jigneshsolanki** [comment]
@Janaka-Steph It will be lost on component unmount, we can't track progress unless it is coming from the server in API

**Comment by Janaka-Steph** [comment]
See https://github.com/premAI-io/prem-daemon/pull/93
