### ISSUE TITLE
Bug Backend URL Caching on desktop app

### ISSUE THREAD

**Issue by filopedraz** [premAI-io/prem-app#276]
### Steps 

- User runs the desktop app
- User changes the settings backend_url with a remote value
- User exits the desktop app
- User reopens the desktop app and he is stuck at system check because it's checking the remote value

### Possible Solution

Disable the possibility to change backend url when running the desktop app.

**Comment by filopedraz** [comment]
@tiero what do you think?

**Comment by tiero** [comment]
> Disable the possibility to change backend url when running the desktop app.

we should make possible to change the backend URL at startup instead, connecting to remote daemon from desktop is great

**Comment by filopedraz** [comment]
You mean in the System Checks view?

**Comment by tiero** [comment]
Yes. in case of error on the daemon connection, we should highlight to change it
