### ISSUE TITLE
Vicuna-7b chat reply stops before end

### ISSUE THREAD

**Issue by Janaka-Steph** [premAI-io/prem-app#280]
https://www.loom.com/share/8723218d5a5e4dbb98dea751b5aab61a?sid=8dd1f54f-2711-46eb-a2f5-7d08288426d2

@filopedraz Is it because of a token limit or is it a bug?

**Comment by filopedraz** [comment]
Before token limit. The total amount of tokens (input + output) for vicuna is only 512
