### ISSUE TITLE
Caddy based solution broken?

### ISSUE THREAD

**Issue by draput** [premAI-io/prem-app#324]
I used the prem_app since reading about it on the langchain blog with no major issues. I used to git pull from time to time and rebuild the docker container. After doing this today, I have realized that the app is not served any more on port 1420, but through caddy on port 8000. However, its crashing on my machine (Docker Desktop on Windows 10 with WSL container). Here is the crash from my browser:

[plugin:vite-plugin-eslint] /app/src/main.tsx
   1:74  error  Delete `␍`  prettier/prettier
   2:27  error  Delete `␍`  prettier/prettier
   3:41  error  Delete `␍`  prettier/prettier
   4:1   error  Delete `␍`  prettier/prettier
   5:31  error  Delete `␍`  prettier/prettier
   6:25  error  Delete `␍`  prettier/prettier
   7:1   error  Delete `␍`  prettier/prettier
   8:38  error  Delete `␍`  prettier/prettier
   9:20  error  Delete `␍`  prettier/prettier
  10:15  error  Delete `␍`  prettier/prettier
  11:35  error  Delete `␍`  prettier/prettier
  12:16  error  Delete `␍`  prettier/prettier
  13:7   error  Delete `␍`  prettier/prettier
  14:5   error  Delete `␍`  prettier/prettier
  15:4   error  Delete `␍`  prettier/prettier
  16:1   error  Delete `␍`  prettier/prettier
  17:76  error  Delete `␍`  prettier/prettier
  18:21  error  Delete `␍`  prettier/prettier
  19:47  error  Delete `␍`  prettier/prettier
  20:14  error  Delete `␍`  prettier/prettier
  21:27  error  Delete `␍`  prettier/prettier
  22:23  error  Delete `␍`  prettier/prettier
  23:3   error  Delete `␍`  prettier/prettier

✖ 23 problems (23 errors, 0 warnings)
  23 errors and 0 warnings potentially fixable with the `--fix` option.
/app/src/main.tsx
    at formatError (file:///app/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:43950:46)
    at TransformContext.error (file:///app/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:43946:19)
    at TransformContext.transform (file:///app/node_modules/vite-plugin-eslint/dist/index.mjs:1:1989)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (file:///app/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:44240:30)
    at async loadAndTransform (file:///app/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:54896:29)
    at async viteTransformMiddleware (file:///app/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:64291:32

**Comment by draput** [comment]
Adding "endOfLine": "lf" to .prettierrc.json and than running

npm install -g yarn
npx yarn add --dev prettier
npx yarn prettier

solved the problem.

**Comment by Janaka-Steph** [comment]
My guess is that you have to reinstall all node modules. Adding a rule to `prettierrc.json` should not be necessary, I don't reproduce your error.

**Comment by Janaka-Steph** [comment]
We changed the Docker setup. Feel free to reopen an issue if it's not working for you.

**Comment by draput** [comment]
My issue persists in the current version, however the workaround described above still works. 

My git config core.autocrlf is set to true.
