### ISSUE TITLE
Consider backend solution for Aider

### ISSUE THREAD

**Issue by marvin-hansen** [premAI-io/prem-app#345]
https://github.com/paul-gauthier/aider

There is currently a hacky C++ server for self hosted lang models for Aider. Setting this up isn't exactly great. 

I think a complete end to end solution with state of the art coding language models would make an excellent freemium business model with a free OSS solution and improved (paid) support and team management for companies. I wouldn't want my code uploaded to OpenAI / Microsoft but for self hosting I would welcome a more comprehensive and complete solution than what's available now. 

Just sharing the idea. 

Great work so far.

**Comment by filopedraz** [comment]
Thanks @marvin-hansen
