### ISSUE TITLE
Download hangs on Ubuntu server

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#357]
I am stuck on downloading Redis for more than 20 minutes, it never shows a progress update. I am on a Paperspace A100 instance.

<img width="1482" alt="image" src="https://github.com/premAI-io/prem-app/assets/3596602/bedcc73d-c246-4716-a2ba-794694ccfb87">

--- 

In comparison it took 10 seconds to complete the docker pull from CLI

<img width="873" alt="image" src="https://github.com/premAI-io/prem-app/assets/3596602/8f7f8d92-48b1-4243-9b82-29af76a783cb">

**Comment by tiero** [comment]
PS: Every 10 seconds the daemon logs 
`2023-10-02 21:47:17 ERROR    An error occurred: argument of type 'NoneType' is not iterable`

**Comment by filopedraz** [comment]
@casperdcl are you working on this on the daemon side?
