### ISSUE TITLE
With Domain enabled, it expects to find `/assets` on BASE Path

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#360]
if my domain is `tiero.ai`, the app will expect the image on `https://tiero.ai/assets/brand-logo-21c75635.svg`

**Comment by Janaka-Steph** [comment]
What is the right path?

**Comment by tiero** [comment]
You tell me :) the browser was not able to download any statinassets

**Comment by Janaka-Steph** [comment]
ok
