### ISSUE TITLE
Fetch domains on /settings page

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#361]
I have restarted the app after adding a Domain (via DNS record), but I see `No Domains Connected Yet`

If I try to connect a domain again, I will get error `404 page not found`

**Comment by sekulicd** [comment]
@tiero how did you restart it?

**Comment by tiero** [comment]
> @tiero how did you restart it?

sorry, I mean reload the page going to my domain instead of IP.

**Comment by tiero** [comment]
We should fetch the connected domains in `/settings` page (if we have the endpint to GET that @sekulicd )

**Comment by sekulicd** [comment]
> We should fetch the connected domains in `/settings` page (if we have the endpint to GET that @sekulicd )

If domain is created it can be fetched on from dnsd on /dns/existing path, if dns is created, as with other services, it should be reachable on IP/dns/existing + header, if created dnsd.subdomain/dns/exising without header.
