### ISSUE TITLE
Service: it does not honor the Invoke Method baseUrl

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#363]
If you go on a domain connected instance on linux, the Chat UI for example does not invoke correctly `llama-2-13b-chat.tiero.ai/v1/chat/completions` but calls `https://premd.tiero.ai:8230/v1/chat/completions`

The use of backendUrl is wrong here https://github.com/premAI-io/prem-app/blob/ae5c589a35cfb0a748a2c776a601ee0b31b17492/src/shared/hooks/usePremChatStream.ts#L63

**Comment by Janaka-Steph** [comment]
I don't think the use of backendUrl is wrong. It is created from this code, where the bug should be:
```
export const getBackendUrl = () => {
  let backendURL = "http://localhost:54321";
  const isBackendSet = () => {
    return (
      ((window as any).VITE_BACKEND_URL !== undefined || import.meta.env.VITE_BACKEND_URL) &&
      ((window as any).VITE_BACKEND_URL !== "" || import.meta.env.VITE_BACKEND_URL !== "")
    );
  };
  if (isBackendSet()) {
    backendURL = (window as any).VITE_BACKEND_URL || import.meta.env.VITE_BACKEND_URL;
  }
  if (isPackaged()) {
    backendURL = `${window.location.protocol}//${window.location.host}/`;
  }
  if (isProxyEnabled() && !isIP(window.location.host)) {
    const arr = backendURL.split("://");
    backendURL = arr[0] + "://premd." + arr[1];
  }
  return backendURL;
};
```

**Comment by filopedraz** [comment]
```ts
backendURL = arr[0] + "://premd." + arr[1];
```

Do you see that it points to `premd` instead of `service_id` (`llama-2-13b-chat`).
