### ISSUE TITLE
[binary] Backend state

### ISSUE THREAD

**Issue by Janaka-Steph** [premAI-io/prem-app#388]
Yesterday I added simple persistent storage to the Rust backend to save static service manifest + dynamic service state. 
Putting more thought into it, I don't think we need to have persistent storage at all. 

The backend state we are talking about here is composed of: running, downloaded, isDownloading, enoughMemory (free memory), enoughSystemMemory (total memory), enoughStorage.

This data is not user settings that should be stored, it is dynamic values that can change.

To implement running I would rather check the Tauri state (state.running_services on binary branch).
To implement downloaded we have to check that all files are fully downloaded. It is a bit tedious but that way we are sure that this state is correct.
To implement isDownloading I would also rather check Tauri state rather than using persistent store.
To implement enoughMemory it has to be a runtime check since this value is dynamic.
enoughSystemMemory could in theory change
enoughStorage it has to be a runtime check since this value is dynamic.

What do you think?

**Comment by filopedraz** [comment]
Yep, I agree. Persistent storage is not necessary.
