### ISSUE TITLE
[binary] GET /services/{service_id} returns 404 on localhost 

### ISSUE THREAD

**Issue by Janaka-Steph** [premAI-io/prem-app#396]
Testing the binary branch as Docker/web environment on localhost.

GET http://localhost:54321/v1/services/ 
=> 200

GET http://localhost:54321/v1/service/vicuna-7b-q4
=> 400 Not found

Steps to reproduce:
Prem Daemon, main branch
```
docker build -t premd .
docker run -it -v /var/run/docker.sock:/var/run/docker.sock -p 54321:8000 --name premd -e PREM_REGISTRY_URL=https://raw.githubusercontent.com/premAI-io/prem-registry/main/manifests.json --rm premd
```

Prem App
- No env vars, all commented
- `yarn dev`

**Comment by filopedraz** [comment]
@Janaka-Steph wrong url. You should point to `/v1/services/{service_id}`. You are missing an `s`.

**Comment by Janaka-Steph** [comment]
Oh crap, thank you
