### ISSUE TITLE
Tauri Binary: Support side-loading of manifest at runtime

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#398]

**Comment by Janaka-Steph** [comment]
The Custom Service Cards are only displayed in dev mode.

**Comment by tiero** [comment]
It should be possible from settings to enable the "dev mode" no?

**Comment by Janaka-Steph** [comment]
Ok but in that case we should remove it as a env var no?

**Comment by tiero** [comment]
Yes, I would prefer to be available to every-body, also in production releases app (not urgent for this sprint tho)
