### ISSUE TITLE
Tauri: rename the identifier to prem-app and not prem.tauri.dev

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#400]

**Comment by Janaka-Steph** [comment]
`identifier` should be in reverse domain name notation https://tauri.app/v1/api/config/#bundleconfig.identifier

We can also add shortDescription, longDescription, category, ...

**Comment by Janaka-Steph** [comment]
Also in cargo.toml we have
[package]
  authors = ["you"]
  description = "A Tauri App"
  edition = "2021"
  license = ""
  name = "prem-app"
  repository = ""
  version = "0.0.32"

**Comment by tiero** [comment]
`io.premai.app` then

**Comment by Janaka-Steph** [comment]
<img width="938" alt="Screenshot 2023-10-25 at 11 57 08" src="https://github.com/premAI-io/prem-app/assets/4022128/4bf9b726-a775-47d4-85ac-6a885af3edb8">

The .app extension causes issue

**Comment by Janaka-Steph** [comment]
io.prem.ai ? @tiero

**Comment by tiero** [comment]
`io.premai.prem-app` ?

**Comment by Janaka-Steph** [comment]
ok
