### ISSUE TITLE
[Binary] Mistral model not configured properly

### ISSUE THREAD

**Issue by Janaka-Steph** [premAI-io/prem-app#401]
<img width="959" alt="Screenshot 2023-10-24 at 23 31 41" src="https://github.com/premAI-io/prem-app/assets/4022128/fce2777e-7188-4f5f-9e97-a6f448cdb9ed">

**Comment by casperdcl** [comment]
I think @biswaroop1547 is going to hardcode a fixed template for OpenOrca.

in future maybe having a configurable prompt might be part of [this manifest.json proposal](https://github.com/premAI-io/prem-registry/pull/88#discussion_r1368454421)

**Comment by biswaroop1547** [comment]
added a solution for current chat services (only implemented and working for Mistral models) - https://github.com/premAI-io/prem-services/pull/124
Requesting reviews 🙏🏻
