### ISSUE TITLE
[binary] Stop service doesn't kill the process

### ISSUE THREAD

**Issue by Janaka-Steph** [premAI-io/prem-app#406]
Start, then stop a service
You can check processes with `lsof -i -P -n | grep LISTEN`

**Comment by swarnimarun** [comment]
It's working correctly for me with tabby could you send the reproduction steps?

**Comment by Janaka-Steph** [comment]
I have the bug with Mistral

**Comment by swarnimarun** [comment]
Yep Mistral CLI seems to be broken. I believe it spawns a detached service, let me check it out a bit more.
