### ISSUE TITLE
Add tag option "Show only available models" to filter not available one

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#413]
I would add a checkbox or toggle on the top right that says "Show only available services" that hides all the not usable services. It's ok to start "un-checked" or "un-toggled"

_Originally posted by @tiero in https://github.com/premAI-io/prem-app/issues/386#issuecomment-1779155540_

**Comment by Janaka-Steph** [comment]
@johnsBeharry Please can you provide me a svg icon that represent availability, in the same style as the existing tags https://github.com/premAI-io/static.premai.io/tree/main/daemon/interfaces

**Comment by tiero** [comment]
Can you use an emoji for no? Like `💻  Available on this computer`
