### ISSUE TITLE
chat window doesnt grow when typing long prompt

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#429]
thats like a super long prompt and i think it throws an error message casue its too many tokens. would be nice to see that the error message says too long of a prompt or something

![image](https://github.com/premAI-io/prem-app/assets/3596602/9c1d5990-034b-405e-899e-04e31e5f06be)

**Comment by Janaka-Steph** [comment]
Using Mistral, in console I can see error `Failed to load resource: cannot parse response` (not sure if you are refering to this one).
But the lib "@microsoft/fetch-event-source" we use for Chat requests returns only an error `Load Failed` without the detail message `cannot parse response` or something else.
I suppose the server is not returning the full error properly?

**Comment by tiero** [comment]
I thought the Load failed was coming from the model not actually loaded 🤔  seems then a catch-all error, not great. Any suggestion? @filopedraz

**Comment by filopedraz** [comment]
The problem is the microsoft lib. Better to have as ChatGPT a generic error message: `Failed to Generate Response. Please retry in a few moments`

**Comment by Janaka-Steph** [comment]
This is the code:
```
 onerror: (err: AxiosError) => {
          const errorMessage = `Something went wrong: ${err.message || ""}`;
          setLoading(false);
          setIsError(true);
          setTempQuestion("");
          toast.error(errorMessage);
          throw new Error(errorMessage);
        },
```
`err.message` is `Loaded Failed`.
I may be wrong but server should be able to return the full error.

**Comment by filopedraz** [comment]
This is the python code for the stream response

```python


async def generate_chunk_based_response(body):
    chunks = model.generate(
        messages=body.messages,
        temperature=body.temperature,
        top_p=body.top_p,
        n=body.n,
        stream=body.stream,
        max_tokens=body.max_tokens,
        stop=body.stop,
        presence_penalty=body.presence_penalty,
        frequence_penalty=body.frequence_penalty,
        logit_bias=body.logit_bias,
        n_threads=body.n_threads,
    )
    for chunk in chunks:
        yield f"event: completion\ndata: {json.dumps(chunk)}\n\n"
    yield "event: done\ndata: [DONE]\n\n"


@router.post("/chat/completions", response_model=ChatCompletionResponse)
async def chat_completions(body: ChatCompletionInput):
    try:
        if body.stream:
            return StreamingResponse(generate_chunk_based_response(body), media_type="text/event-stream")
        return model.generate(
            messages=body.messages,
            temperature=body.temperature,
            top_p=body.top_p,
            n=body.n,
            stream=body.stream,
            max_tokens=body.max_tokens,
            stop=body.stop,
            presence_penalty=body.presence_penalty,
            frequence_penalty=body.frequence_penalty,
            logit_bias=body.logit_bias,
            n_threads=body.n_threads,
        )
    except ValueError as error:
        raise HTTPException(
            status_code=400,
            detail={"message": str(error)},
        )
```

As you can see, we are not returning `Loaded Failed` as the message. I don't know if we have control over this aspect.

**Comment by Janaka-Steph** [comment]
Would be interesting to log the error before `raise`

**Comment by filopedraz** [comment]
But are you getting 400 status code?

**Comment by Janaka-Steph** [comment]
No
