### ISSUE TITLE
Public Name is not shown on health monitor

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#441]
Using latest commit https://github.com/premAI-io/prem-app/commit/4469919e0d27b0f7301db1a44e17e6d1867f0972

I am contributing from a Mac and those 3 dots seems to be me, but the name is not advertised

![image](https://github.com/premAI-io/prem-app/assets/3596602/22c18937-e7fb-4875-89b9-d49213e62cb9)

**Comment by tiero** [comment]
Wait on our own monitor is shown 🤔 Alotugh is very slow compared to the petals one

<img width="936" alt="image" src="https://github.com/premAI-io/prem-app/assets/3596602/9a32f03c-0ad1-4f9a-a862-1845b8ef8a57">

**Comment by filopedraz** [comment]
Weird, we use the same exact APIs. Let's debug it together on Monday

**Comment by johnsBeharry** [comment]
Hey marko, what do you mean it's slow? Slow to update or something else?

**Comment by tiero** [comment]
Probably it's a cache issue to prevent referchting new API compared to health monitor

**Comment by johnsBeharry** [comment]
Ok will look into it. Could you also add me to the vercel ?
