### ISSUE TITLE
In Service Detail page avoid to block UI drawing if the /stats-all endpoint

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#457]
Isolate the fetching of data in this component only, so we won't stop the user from entering the service page, we keep the component with a "Loading ..." placeholder

**Comment by Janaka-Steph** [comment]
Actually this is already the case. `v1/stats/${serviceId}` is called in <ServiceResourceBars/> component inside Detail page. It should not block the loading of Detail page.

**Comment by tiero** [comment]
Replaced by https://github.com/premAI-io/prem-daemon/issues/175
