### ISSUE TITLE
Petal processes kill

### ISSUE THREAD

**Issue by nsosio** [premAI-io/prem-app#464]
Replace `kill -s SIGKILL` of petal processes with:

- `SIGINT` first with a timeout
- `SIGTERM` first with a timeout
- `SIGKILL`

**Comment by swarnimarun** [comment]
Note: SIGINT is windows whereas SIGTERM is unix.

If if just want timeout on unix then, `--timeout` flag exists on `/usr/bin/kill` (not on shell kill).

You can write it as, 
```sh
/usr/bin/kill --timeout 1000 TERM --signal QUIT ${PID_TO_KILL}
```
