### ISSUE TITLE
Wrong invocation of prem-service chat

### ISSUE THREAD

**Issue by sekulicd** [premAI-io/prem-app#503]
Prem-App is sending request to chat prem-service's on wrong path:

Before dns it is sending it to:
http://{IP}/v1/chat/completions 
and it should send on:
http://{IP}/gpt4all-lora-q4/v1/chat/completions

After dns is created it is sending to:
https://{DOMAIN}/v1/chat/completions
and it should send on:
https://gpt4all-lora-q4.{DOMAIN}/v1/chat/completions

@tiero

**Comment by tiero** [comment]
Duplicate issue of https://github.com/premAI-io/prem-app/issues/474
