### ISSUE TITLE
Chat: Escape single and double quotes from messages before sending over request

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-app#520]

**Comment by tiero** [comment]
Can you try with special characters? liek #, $, \, /, etc..

**Comment by Janaka-Steph** [comment]
This is your prompt?
I get error "Failed to load resource: cannot parse response" in Mistral 128k

**Comment by Janaka-Steph** [comment]
Smaller prompt with special chars works fine

**Comment by tiero** [comment]
cc/ @filopedraz Can you share a short prompt with special chars that gives you an error?

For checking logs
```
cat ~/Library/Application\ Support/io.premai.prem-app/models/<service_id>/<service_id>/log
```

**Comment by Janaka-Steph** [comment]
Is it still a thing?

**Comment by tiero** [comment]
CLosing for now, let's re-open @filopedraz  if you find anything the client chat should do!
