### ISSUE TITLE
Correction in API Base URL for chat/completion requests

### ISSUE THREAD

**Issue by sekulicd** [premAI-io/prem-app#539]
The current base URL used for chat/completion requests is pointing to an incorrect host(62.4.58.131), causing a failure in request processing.

http://62.4.58.131/gpt4all-lora-q4/v1/chat/completions

@tiero @Janaka-Steph

**Comment by tiero** [comment]
This seems to be drives from your local IP of your home network?

**Comment by tiero** [comment]
this seems connected to https://github.com/premAI-io/prem-app/issues/474

**Comment by Janaka-Steph** [comment]
Testing docker locally, you can see that `baseUrl` received from the daemon is wrong. This is my public IP.

<img width="1728" alt="Screenshot 2023-11-11 at 09 49 31" src="https://github.com/premAI-io/prem-app/assets/4022128/9580f7f4-c31e-4c19-9c9a-55068e253c5b">

**Comment by tiero** [comment]
I think that is kinda expected, so we need to think if we want to have a special rule for localhost eventually in the frontend or daemon. This is only for development after all

**Comment by tiero** [comment]
I have a different result instead @Janaka-Steph using https://demo.prem.ninja

The Service Details page shows correctly the baseUrl for LLama service 
<img width="478" alt="image" src="https://github.com/premAI-io/prem-app/assets/3596602/065b26d7-0463-45ec-9c22-9daf98d05392">


But then the playground chat calls the wrong baseUrl ie. 

<img width="556" alt="image" src="https://github.com/premAI-io/prem-app/assets/3596602/03bb781a-d512-4f7f-8551-2908677c4a15">

**Comment by Janaka-Steph** [comment]
Can you check TanStack devtool ?

**Comment by tiero** [comment]
I am on released on `demo.prem.ninja`, is there a way to do from there?

**Comment by tiero** [comment]
I am making a new Docker release using latest main, let's see if it fixes

**Comment by Janaka-Steph** [comment]
We can add devtool on production, hidden and lazy loaded, triggered by a command in browser console

**Comment by Janaka-Steph** [comment]
The front just use service.baseUrl here

**Comment by tiero** [comment]
But baseUrl in the service detail page seems correct

**Comment by tiero** [comment]
Fixed using the latest main!

<img width="1511" alt="image" src="https://github.com/premAI-io/prem-app/assets/3596602/dbe9dfa3-0108-42a4-8240-ae182b3e4587">

**Comment by Janaka-Steph** [comment]
Surprise!
