### ISSUE TITLE
Possible problems while generating POSTGRES_PASSWORD using linux installation script

### ISSUE THREAD

**Issue by MashiPe** [premAI-io/prem-app#557]
Hey guys, first of all, I'm really glad that the project is still active and appreciate all the effort.

Now, onto the problem: I'm not sure if you guys are aware, but there is a flaw with the current method of generating the `POSTGRES_PASSWORD` in the installation script for Linux. There is a possibility of getting the character <kbd>/</kbd>, which can mess up the connection URL for the `dnsd` service. This character should be cleaned in the script, perhaps by replacing it with another character.

**Comment by tiero** [comment]
Thanks for trying it out and reporting.

We are aware and will be fixed next version 

https://github.com/premAI-io/prem-gateway/issues/28

For now simply reinstall again it should luckily pick one without issues

**Comment by tiero** [comment]
Can you try `uninstall.sh` and `install.sh` again? With the gateway version v0.0.6 it should be fixed https://github.com/premAI-io/prem-gateway/pull/30

**Comment by MashiPe** [comment]
Seems to be fixed, I tried on a different PC to avoid any conflict and hard coded a POSTGRES_PASSWORD with a <kbd>/</kbd> in between in the `install.sh` file, and it connected successfully to the database.
